### ISSUE TITLE
Cannot open include file: 'fitz.h'

### ISSUE THREAD

**Issue by WalterShao** [MishaUliutin/MuPDF.WinRT#2]
Hi, 

I am new to this project. I downloaded the source code and tried to build the project on my VS 2012. But got the build error messages:

"error C1083: Cannot open include file: 'fitz.h': No such file or directory (..\Src\MuPDFDoc.cpp)"
"error C1083: Cannot open include file: 'fitz.h': No such file or directory (..\Src\Document.cpp)"

I know fitz.h is one file of MuPDF source code. Would you please let me know how to add the MuPDF files into MuPDF.WinRT project, so that I can pass the build? Thanks a lot. 

BTW, I believe MuPDF.WinRT is for Win8 Store App. That is, I can write a Win8 Store App in C# and invoke the functions in MuPDF.WinRT. Am I correct? 

Walter

**Comment by MishaUliutin** [comment]
Hi,

It looks like you forgot to init and update submodules (I've added mupdf source as submodule to my project).
Unfortunately, I have not finished yet simple build script (for build just by call some bat-file), because there are some issues with build mupdf in ARM architecture with VS2012 compiler (I wrote issue in mupdf bugtracker and I am waiting answer now).
If you want build this project by yourself I've added step by step instruction how to do this (you have to make 2 changes in mupdf code):
https://github.com/MishaUliutin/MuPDF.WinRT/issues/1#issuecomment-13975296
or I can add compiled dll files

> > BTW, I believe MuPDF.WinRT is for Win8 Store App. That is, I can write a Win8 Store App in C# and invoke the >> functions in MuPDF.WinRT. Am I correct?
> > yes

Best Regards,
Misha Uliutin

**Comment by WalterShao** [comment]
Hi, 

Thanks a lot for the replay. After download the latest mupdf source and put into .\MuPDF.WinRT\ThirdParty\mupdf folder, and follow your instructions in issue #1, I can pass the build and generate static library under .\MuPDF.WinRT\ThirdParty\Win8\ARM and WIn32 folders. 

But when I build your wrapper code (.\MuPDF.WinRT\Win8\MuPDFWinRT.sln), I got the a lot errors such as:
      IntelliSense: too few arguments in function call \MuPDF.WinRT\Src\MuPDFDoc.cpp    76  66  MuPDFWinRT

Actually, the above error is fz_bbox not defined, just like issue #1 mentioned. 
I checked the response in issue #1, but still failed to find the way to solve the fx_bbox not defined error. Would you please give more hints? Thanks. 

Walter

**Comment by MishaUliutin** [comment]
Hi,
You should not download manualy mupdf source code, you should use

```
    $ git submodule init
    $ git submodule update
```

As I wrote in instruction, (when I start the latest released version of MuPDF was 1.1, so my code works with 1.1 version and submodule is pointed to 1.1 version). I upgrade my code for 1.2 version ASAP.

Best Regards,
Misha Uliutin

**Comment by WalterShao** [comment]
Hi, 

I got it. Two key points I missed: (a) I was not familiar with git commands (b) I didn't know the MuPDF version should be v1.1.

After fixing that, now I can build your wrapper (MuPDFWinRT.sln) successfully, and going to write some test programs in c#. Also look forward to your demo program in c# if possible. Thanks a lot.

Walter

**Comment by MishaUliutin** [comment]
Hi,
no problem, and don't forget that you have to use different dlls for different architecture (ARM or x86).

Best Regards,
Misha Uliutin
